### PR TITLE
Added Redistributables for VS2015. Updated 2012 and 2013.

### PR DESCRIPTION
**Pull request by jpfeuffer**
Renamed redist of 2012 to follow naming convention. Version can be found out by executing and cancelling. Updated other redistributables starting from 2012.

Actually this whole redist versioning is a mess. I think the best way is to only build and deploy on the most recent VS updates of a specific version and also only use the most recent Redistributable. This ensures that they are compatible. I tried inferring compatibility by comparing the full version numbers of the Devenv executable and the VCRedist installer but this does not seem to always work out.

Current state:
2012 update 4 (which is also the latest update for VS)
2013 update 2 (there seem to be no updates since then. VS is at update 5)
2015 release (there seem to be no updates until newest VS2015 update 3)

### CODE REVIEW

**Comment by cbielow** [comment]
the vcredist names need to be entered manually in the cfg file anyways - so why not stick with the descriptive names while still using the the latest update?

**Comment by jpfeuffer** [comment]
I was trying to automatically choose the vcredist depending on the visual studio command line that was used for building. Therefore, on the new build machines, I am trying to pass parameters from the build to the packaging to reduce possible errors. But yes, I can add the updates to all exes and use some regexes/wildcards to pick the right one (they are imho just a mess in batch).

**Comment by jpfeuffer** [comment]
Done. I also checked the old ones and looked up their version. SP is service pack, UPD is update and nothing means RTM=release.

**Comment by jpfeuffer** [comment]
One thing that bugs me, is that on their webpage, the pwiz guys say that one needs vcredist2008sp1, but we deliberately include vcredist2010sp1 for it. Does somebody know if this is still correct?

**Comment by timosachsenberg** [comment]
the solution file in the pwiz repository is now at: 

```
# Visual Studio 2013
VisualStudioVersion = 12.0.21005.1
```

and while I don't know the details it seems to install the runtimes from VC9 to VC12:

 https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/scripts/wix/pwiz-setup.wxs.template

```
          <Merge Id="CRT9" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC90_CRT_x86_x64.msm" DiskId="1" />
            <Merge Id="MFC9" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC90_MFC_x86_x64.msm" DiskId="1" />
            <Merge Id="CRT9_policy" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\policy_9_0_Microsoft_VC90_CRT_x86_x64.msm" DiskId="1" />
            <Merge Id="MFC9_policy" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\policy_9_0_Microsoft_VC90_MFC_x86_x64.msm" DiskId="1" />

            <Merge Id="CRT10" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC100_CRT_x64.msm" DiskId="1" />
            <Merge Id="MFC10" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC100_MFC_x64.msm" DiskId="1" />

            <Merge Id="CRT11" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC110_CRT_x64.msm" DiskId="1" />
            <Merge Id="OMP11" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC110_OpenMP_x64.msm" DiskId="1" />

            <Merge Id="CRT12" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC120_CRT_x64.msm" DiskId="1" />
            <Merge Id="MFC12" Language="0" SourceFile="$(env.ProgramFiles)\Common Files\Merge Modules\Microsoft_VC120_MFC_x64.msm" DiskId="1" />
```

**Comment by jpfeuffer** [comment]
Ah I see. Thanks for looking into it. But that would mean that they meanwhile seem to install all the requirements and we do not need to package the additional VSRedist?

**Comment by timosachsenberg** [comment]
I can take a look at the actually installed files when I am back on my windows machine on monday.

**Comment by jpfeuffer** [comment]
Is there an update on if the VCRedist for pwiz is actually needed?

**Comment by timosachsenberg** [comment]
ok I extracted the MSI installer file from pwiz using:

```
msiexec /a drive:\filepath\to\MSI\file /qb TARGETDIR=drive:\filepath\to\target\folder
```

as Administrator.
And I get:

```
msvcr71.dll

mfcm90.dll
mfcm90u.dll
mfc90.dll
mfc90u.dll
msvcp90.dll
msvcr90.dll
msvcm90.dll

mfc100.dll
mfc100u.dll
mfcm100.dll
mfcmu100.dll
msvcp100.dll
msvcr100.dll
```

**Comment by jpfeuffer** [comment]
Thanks. Ok that seems like additionally packaging vcredist2010_x86_sp1.exe is not needed (anymore). We can try to remove it at some point. Currently installing it twice should not be a problem, though.

**Comment by timosachsenberg** [comment]
I think we need to install it because we don't include the full pwiz installer but only the files in the pwiz folder. (The redistributables are usually copied to the win system folder by the pwiz installer).

**Comment by jpfeuffer** [comment]
Aaah I see. Then we have to hope that it works without installing msvc9. Given that it worked before, I would think so.

**Pull request merged**
